### ISSUE TITLE
Spons brochure and College Representative page

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/Frontend-2016#13]
Waiting for Spons and design team.

**Comment by chinnichaitanya** [comment]
Got the designs. Need to complete the College Representative page also.

**Comment by anirudhravichandran** [comment]
Sponsors and College Rep page completed

**Comment by chinnichaitanya** [comment]
@anirudhravichandran Make it responsive. I do not see any scrolling-effects in the Spons brochure.
Also, the Spons brochure has multiple pages with a menu on the top. Check them once.

**Comment by chinnichaitanya** [comment]
Any updates ?

**Comment by chinnichaitanya** [comment]
@anirudhravichandran Push the completed code ASAP.

**Comment by chinnichaitanya** [comment]
@anirudhravichandran I see it is still not complete. Complete it ASAP.
