### ISSUE TITLE
Contact Us page

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/Frontend-2016#14]
Waiting for design.

**Comment by chinnichaitanya** [comment]
We got the design.
It is **contact-us-1.jpg** and **contact-us-2.jpg** in the [drive folder](https://drive.google.com/drive/u/0/folders/0B41bGb29AKWqMURrd1lfVWR6WE0)

**Comment by chinnichaitanya** [comment]
@SuganPrabu96 
- Regarding the hover animation, make it similar to [this](http://www.shaastra.org/2015/main/php/pages/eventlist.php?category=Department+Flagship) except that the text should not fade away.
- And regarding what to show on clicking each box, make it similar to last year. Launch a modal and show the data there. [Here](http://www.shaastra.org/2015/main/php/pages/contact.php).

**Comment by sumanasusmitha** [comment]
Updates regarding hover animation and launching a model on clicking!?

**Comment by chinnichaitanya** [comment]
Hey complete this asap. 
Also [this](https://github.com/ShaastraWebops/Frontend-2016/blob/master/personal/SuganPrabu/contact-us-script.js#L30) line is not commented. It might lead to errors. Fix it.
And also, in the `contact-us-styles.css` file, you can reduce that `nth-child` thingy to one single function by using SASS. Do it using it.

**Comment by chinnichaitanya** [comment]
Ping @SuganPrabu96

**Comment by chinnichaitanya** [comment]
@SuganPrabu96 Complete this ASAP.
