### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/Frontend-2016#2]
Need to make the home page similar to the website http://solutions.3mindia.co.in/wps/portal/3M/en_IN/3M-Tech3/Technology/

So for that, we need to make the image follow the cursor.
Make the hexagon layout using bootstrap classes.

**Comment by ojasvita25** [comment]
acknowledged

**Comment by chinnichaitanya** [comment]
Any updates ?

**Comment by ojasvita25** [comment]
i have started working . Done a bit of the layout.

**Comment by chinnichaitanya** [comment]
Any updates ?

**Comment by ojasvita25** [comment]
done with the layout .working on the js part.

On Thu, Jun 18, 2015 at 10:13 AM, Chinni Chaitanya <notifications@github.com

**Comment by sumanasusmitha** [comment]
push your code ,reply with update

**Comment by ojasvita25** [comment]
i pushed.do check.

**Comment by ojasvita25** [comment]
Is the robot's hand movement fine ? and any other changes i need to make?

**Comment by chinnichaitanya** [comment]
Make the following changes,
- [ ] Hide the hand movement and the Shaastra logo in small screens.
- [ ] You haven't pushed `bootstrap-responsive.css` but you have put it in the code. Check [here](https://github.com/ShaastraWebops/Frontend-2016/blob/master/personal/ojasvita25/homepage.htm#L9).
- [ ] Change the extension of the `homepage.htm` file to `.html`.
- [ ] Indent your `homepage.css` and `homepage.js` code. Change the indentation settings in the text-editor you use to **2-spaces**.
- [ ] Why use complex names like `tooltipSpanr` nad `tooltipSpan` ?? Can't you just use `leftHand` and `rightHand` ?? Same thing applies to the `id` names to elements ([here](https://github.com/ShaastraWebops/Frontend-2016/blob/master/personal/ojasvita25/homepage.js#L21-L22)).
- [ ] In my browser, I find a *vertical scroll-bar* appearing. Fix that.

Robot's hand movement is slight unstable. try implementing some other method (if you find any) for following the cursor.

Update once done.

**Comment by chinnichaitanya** [comment]
I've updated a couple more tasks. Once check.

**Comment by ojasvita25** [comment]
i have pushed the updated one and that bootstrap-responsive.css  file was
not necessary. I've made a bit changes to the robot's hand movement also .

**Comment by chinnichaitanya** [comment]
@ojasvita25 Fix these things,
It is not responsive at all.
Don't use `onclick`. Use `ng-click` of AngularJS.
An on clicking on any box, the hand movement is abrupt. Check that.

**Comment by ojasvita25** [comment]
I have pushed a bit updated one. some work left in responsiveness.

**Comment by sumanasusmitha** [comment]
Handmovement is fine.The issues which chinni mentioned are still there, check them again.

**Comment by chinnichaitanya** [comment]
@ojasvita25 Complete them asap.

**Comment by ojasvita25** [comment]
pushed updates.

**Comment by chinnichaitanya** [comment]
Looks good :+1:

**Comment by chinnichaitanya** [comment]
@ojasvita25 The design team has given the updated pics of the *hand*. Check it [here](https://drive.google.com/drive/u/0/folders/0B41bGb29AKWqX3gxQnVmZnoxcTg) and use the new images in your code.

**Comment by chinnichaitanya** [comment]
@ankan007 Make the *onclick animation* same as the one given in the [site](http://solutions.3mindia.co.in/wps/portal/3M/en_IN/3M-Tech3/Technology/) and redirect to that particular page.

**Comment by ankan007** [comment]
Added the animation.

On Sun, Aug 9, 2015 at 10:33 PM, Chinni Chaitanya <notifications@github.com>
wrote:

> @ankan007 <https://github.com/ankan007> Make the *onclick animation* same
> as the one given in the site
> <http://solutions.3mindia.co.in/wps/portal/3M/en_IN/3M-Tech3/Technology/>
> and redirect to that particular page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShaastraWebops/Frontend-2016/issues/2#issuecomment-129217379>
> .
>



-- 
Ankan Paul
Civil Engineering Sophomore
IIT Madras

**Comment by chinnichaitanya** [comment]
@ankan007 For those 6 boxes in the home page, implement the hover animation as there in [this](http://demo.kingkongthemes.com/ruby/r-creative/) website. Scroll down a bit and you will find the *creative 1* to *creative 6* boxes.

**Comment by chinnichaitanya** [comment]
@ankan007 Updates on this ?

**Comment by ankan007** [comment]
Working on it. Will push once done.

On Tue, Aug 25, 2015 at 12:23 AM, Chinni Chaitanya <notifications@github.com
> wrote:

> @ankan007 <https://github.com/ankan007> Updates on this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShaastraWebops/Frontend-2016/issues/2#issuecomment-134337346>
> .
>



-- 
Ankan Paul
Civil Engineering Sophomore
IIT Madras

**Comment by ankan007** [comment]
svg animation added.

On Tue, Aug 25, 2015 at 10:23 PM, Ankan Paul <ankan.paul05@gmail.com> wrote:

> Working on it. Will push once done.
>
> On Tue, Aug 25, 2015 at 12:23 AM, Chinni Chaitanya <
> notifications@github.com> wrote:
>
>> @ankan007 <https://github.com/ankan007> Updates on this ?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ShaastraWebops/Frontend-2016/issues/2#issuecomment-134337346>
>> .
>>
>
>
>
> --
> Ankan Paul
> Civil Engineering Sophomore
> IIT Madras
>



-- 
Ankan Paul
Civil Engineering Sophomore
IIT Madras
