### ISSUE TITLE
Eventlist page

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/Frontend-2016#3]
This might take some time to do. There are many things to be done in this.

As of now, put dummy images and data. 

Refer **6.jpg** and **5.jpg** in the [drive](https://drive.google.com/folderview?id=0B41bGb29AKWqMURrd1lfVWR6WE0&usp=sharing) folder.

Need to Google a lot for searching a suitable module compatible with AngularJS.

**Comment by chinnichaitanya** [comment]
I want @ankan007 and @shahlakp both of you to check this. This will be used for lectures page also.

**Comment by ankan007** [comment]
Acknowledged.

Regards.

On Sun, Jun 7, 2015 at 4:20 AM, Chinni Chaitanya <notifications@github.com>
wrote:

> I want @ankan007 <https://github.com/ankan007> and @shahlakp
> <https://github.com/shahlakp> both of you to check this. This will be
> used for lectures page also.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShaastraWebops/Frontend-2016/issues/3#issuecomment-109655587>
> .
>



-- 
Ankan Paul
Civil Engineering Sophomore
IIT Madras

**Comment by shahlakp** [comment]
acknowledged

**Comment by chinnichaitanya** [comment]
Any updates ?

**Comment by ankan007** [comment]
Layout done and a bit of styling also. Need to add bootstrap classes for
responsiveness and also do animations.

On Wed, Jun 10, 2015 at 1:53 AM, Chinni Chaitanya <notifications@github.com>
wrote:

> Any updates ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShaastraWebops/Frontend-2016/issues/3#issuecomment-110494064>
> .
>



-- 
Ankan Paul
Civil Engineering Sophomore
IIT Madras

**Comment by chinnichaitanya** [comment]
Any updates ?

**Comment by sai-akshaya** [comment]
It'll be better if the glyphicon for scrolling, social networking navs and insti/saarang logos (basically footer) is sticking. 
(Already implemented on events page)

**Comment by chinnichaitanya** [comment]
@ankan007 That is not the animation expected. On pressing the `left` and `right` buttons in the keyboard, the whole page is moving. It should not happen. Only the verticals alone must scroll.
Fix that first. Check [this](https://github.com/FluidApps/bootstrap-horizon) out.

**Comment by chinnichaitanya** [comment]
@ankan007 @shahlakp 
Any updates ??

**Comment by sumanasusmitha** [comment]
"On pressing the left and right buttons in the keyboard, the whole page is moving. It should not happen. Only the verticals alone must scroll", This issue is not cleared yet !!
Total content in the page is not occupying the whole window when opened in mobile browser.
Reply with updates!!

**Comment by ankan007** [comment]
My laptop was submitted to the service center due to some hardware problems
and it has been formatted. I had informed Chinni about this. Sorry for the
inconvenience caused. Will work on the notified things soon.


On Tue, Jul 14, 2015 at 9:49 PM, susmitha <notifications@github.com> wrote:

> "On pressing the left and right buttons in the keyboard, the whole page is
> moving. It should not happen. Only the verticals alone must scroll", This
> issue is not cleared yet !!
> Total content in the page is not occupying the whole window when opened in
> mobile browser.
> Reply with updates!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShaastraWebops/Frontend-2016/issues/3#issuecomment-121295248>
> .
>



-- 
Ankan Paul
Civil Engineering Sophomore
IIT Madras

**Comment by chinnichaitanya** [comment]
@ojasvita25 and @shahlakp Try to complete this page by Wednesday.

**Comment by ojasvita25** [comment]
Pushed updates.

**Comment by chinnichaitanya** [comment]
Nice work! Now try implementing the scroll feature. So if the person scrolls, the *eventlist div* should move horizontally. Also try to customize the horizontal scroll bar and implement smooth scrolling.
