### ISSUE TITLE
Events page

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/Frontend-2016#4]
This page will show all the events of a particular category.

Put dummy data and images.

Refer **8.jpg**, **9.jpg**, **10.jpg**, **11.jpg** in the [drive](https://drive.google.com/folderview?id=0B41bGb29AKWqMURrd1lfVWR6WE0&usp=sharing) folder.

**Comment by chinnichaitanya** [comment]
Hey there are a few things to be fixed,
- [ ] Don't use inline styles. Only use bootstrap classes. For `height`, put it in separate `.css` file but not in the ```style``` attribute.
- [ ] After rotating the event-box, as of now, make the `background-color` *yellow* and put the details on it the date, button etc.,
- [ ] Use bootstrap glyphicon for the *scroll down* thingy.
- [ ] Remove the `<meta>` tags and change the CDN links to the things installed in `bower_components` folder.
- [ ] Indent your code properly. Use 2 spaces for indentation instead of 4 spaces. Have a `space` after `,` `:` etc etc.,
- [ ] The rotate animation doesn't seem to be smooth. Try changing the interval (or) the timing function. 

After completing them push and comment on this thread.

**Comment by chinnichaitanya** [comment]
- [ ] The rotate animation is completely broken. Two boxes are rotating at a time. Fix that.
- [ ] You shouldn't use `bootstrap.min.js` or `bootstrap.js` whild using AngularJS. Remove that. You can use `bootstrap.css` though.
- [ ] For the rotate thingy, initially it should be like **10.jpg** and on hovering, it should be like **11.jpg** in the images in the drive folder. Fix that.
- [ ] The rotate animation is still not smooth. Check that.
- [ ] Indent your code. It is looking very very bad.

After fixing the bugs, immediately *check* in the checkbox. It will help others to track.

**Comment by SuganPrabu96** [comment]
I have pushed with sticking event category to page top on scrolling.

**Comment by chinnichaitanya** [comment]
@SuganPrabu96 Any updates the new animation I have told you to implement ?

**Comment by sumanasusmitha** [comment]
Scrolling is bit is not smooth when tested in chrome

**Comment by chinnichaitanya** [comment]
Regarding the scrolling, there are many plugins available. We can do that later also. Not an issue :)

**Comment by SuganPrabu96** [comment]
I have started working on the animation. I'll try to finish it and push by tomorrow.

**Comment by SuganPrabu96** [comment]
The scrolling is not working properly because of a problem with JSON and array conflict. I will fix it once I get the details from the backend instead of putting them as static data.

**Comment by SuganPrabu96** [comment]
@chinnichaitanya Is the animation in my recent push fine?

**Comment by chinnichaitanya** [comment]
@SuganPrabu96 Awesome. Change the time of the transition to to 1s and try. Increase the speed of the animation.
And regarding the responsiveness, after I change the browser width, it is not proper but after I scroll down, it is rearranging properly. Good work there but check this once.

**Comment by SuganPrabu96** [comment]
Changed transition time to 0.5s. Animation will be happening faster now.

**Comment by chinnichaitanya** [comment]
So this only has the resizing issue left and some cleanup if possible.
