### ISSUE TITLE
Event details page

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/Frontend-2016#5]
This page will show the details of each event.

Put dummy data.

Actually the data will be got through ```$http``` calls. So need to make all things modular so that we can use ```ng-repeat``` and iterate.

Refer **12.jpg** in the [drive](https://drive.google.com/folderview?id=0B41bGb29AKWqMURrd1lfVWR6WE0&usp=sharing) folder.

**Comment by chinnichaitanya** [comment]
Any updates ?

**Comment by sasivarnan619** [comment]
I am starting the work today.
I was out of station.

**Comment by sasivarnan619** [comment]
finished with the left menu bar and the content part

**Comment by sasivarnan619** [comment]
![events](https://cloud.githubusercontent.com/assets/8914628/8082544/acbdbc06-0f9b-11e5-8753-c57b1099def1.png)

**Comment by sasivarnan619** [comment]
so far what i did

**Comment by sasivarnan619** [comment]
is it fine. i did 12.jpg

**Comment by sasivarnan619** [comment]
![evnts latest](https://cloud.githubusercontent.com/assets/8914628/8108909/16329618-1071-11e5-84c1-d0563998ce6c.png)

**Comment by chinnichaitanya** [comment]
Push it into your personal folder and I'll tell if any changes are to be made.

**Comment by sasivarnan619** [comment]
chinni i pushed it.

**Comment by sasivarnan619** [comment]
Chinni i pushed 12.jpg  page  in my personal file. Check it

**Comment by chinnichaitanya** [comment]
There are a few changes to be made.
- [ ] Remove the top navbar you have made. It is a separate component and we need to import it into our `html` file.
- [ ] Put all your styles in a separate `css` file.
- [ ] Remove the CDN links for bootstrap and also the `<meta>` tags. Use the bootstrap files in the `bower_components` folder.
- [ ] Make it responsive. Right now in smaller screens, it is not looking good. In small screens, hide the right navbar and put a small *arrow* button and on clicking it, you should open the *navbar*.
- [ ] Don't use many `divs` for putting the content. You have to place the content in only one `<div>`. You should make it look good with that because the content is not static but dynamic.
- [ ] Don't use inline styles. Put everything in `css` file.
- [ ] Integrate AngularJS to your code. Put a controller and put the raw data in it. That is the exact format you will get the data from the `$http` calls. Use the same data and populate the `html` file. Don't directly put the content in your `html` file. Remember you can't use `bootstrap.min.js` with AngularJS.
- [ ] Preferably don't use `<br>` tags.

After fixing those, push and comment here. Also *tick* those check boxes after you complete each one of them.

**Comment by sasivarnan619** [comment]
i have done changes for small screen.
i gave link to bower_components
decreased the divs for content(only one div)
til i am not done with angularjs part 
i am going out till 18th 
so i will do it on 19th

**Comment by sasivarnan619** [comment]
just check the last update
i seperated css from html

**Comment by chinnichaitanya** [comment]
Again,
- [ ] Remove the top `navbar`. Remove that *chinni* and *search*
- [ ] Why are you adding a unique style class ( `ef`, `ps`, `faq` etc.,) to each *tab* ? We don't know before hand how many tabs will be there so we can't put unique *class* for each tab. 
- [ ] Regarding the AngularJS part, do something like below in the `controller`.
```
var tabs = [{ 'name': 'tab one name', 'data': 'tab one data' }, { 'name': 'tab two name', 'data': 'tab two data' }, ... ];
```
Then you can put have `ng-repeat` in your `html` file and repeat for all the tabs.
On clicking each tab, show the corresponding data.
Don't put static data in the `html` file.
- [ ] You still didn't remove `<meta>` tag in the `html` file.

I'm writing these issues again. These are mentioned in the previous comment and you haven't completed them. 
Also I've told you to *tick* the check boxes after completing each one. You didn't do that also.

**Comment by sasivarnan619** [comment]
the classes for tabs are for the jqery effects on hover.

**Comment by chinnichaitanya** [comment]
Right but you cannot put specific unique class to each tab.

**Comment by sasivarnan619** [comment]
how to put the correct data on clicking the respective tab.

**Comment by chinnichaitanya** [comment]
So in each `object`, you will have a field called `_id` which will be unique. So once you use `ng-repeat`, you need to run a function using `ng-click` and populate the respective content by having a search through that `array` using the `_id` field. For searching through that `array` with respect to `_id`, try to use *plugins* like [lodash](https://github.com/lodash/lodash).

**Comment by sasivarnan619** [comment]
Ok i will check it out.

**Comment by sasivarnan619** [comment]
I put the correct data on clicking the respective tab

**Comment by chinnichaitanya** [comment]
Now what about those classes `ef`, `ps`, `faq` etc ?

**Comment by sasivarnan619** [comment]
Ya those are for jquery effects.

**Comment by chinnichaitanya** [comment]
Why do you need separate JQuery effects ? It is for page transition ?

**Comment by sasivarnan619** [comment]
For tabs. On hower effects

**Comment by sasivarnan619** [comment]
I will try without using many classes

**Comment by chinnichaitanya** [comment]
See the thing is you don't know how many tabs you have before hand. So you got to use `ng-repeat`. There you cannot put unique classes for each tab right ?

**Comment by sasivarnan619** [comment]
Ok

**Comment by sasivarnan619** [comment]
i used ng-repeat. Using that i gave jquery effects.
till only the data part is left

**Comment by sasivarnan619** [comment]
Check the last update.
I used ng repeat.

**Comment by sasivarnan619** [comment]
chinni check the last update.
Classes are given on index numbers.

**Comment by chinnichaitanya** [comment]
@sasivarnan619 Put the JavaScript code in a separate `js` file. Don't mix it with the `html` file.

**Comment by sasivarnan619** [comment]
js code is in seperate files now.

**Comment by chinnichaitanya** [comment]
@sasivarnan619 Check (this)[https://github.com/ShaastraWebops/Frontend-2016/commit/e8ea72530f4d47dbcc1ad4cf151154684174fd4b] comment.

**Comment by sasivarnan619** [comment]
If we give a common class then the color will change for all tabs at same
time if we are over any one of them.

**Comment by chinnichaitanya** [comment]
@sasivarnan619 
No. It is not that way. Check once.

**Comment by chinnichaitanya** [comment]
@sasivarnan619 Where is the progress ??

**Comment by sasivarnan619** [comment]
completed.
when is the meeting tomorrow.

**Comment by sasivarnan619** [comment]
it is done. i added the sponsers down.
