### ISSUE TITLE
Login and registration page

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/Frontend-2016#6]
Try to put them in the same page. 
Use tabs to show login and registration views separately.

Make it similar to current style [here](http://www.shaastra.org/2015/main/php/pages/login.php).

**Comment by chinnichaitanya** [comment]
Any updates ?

**Comment by nitishkumarranjan** [comment]
Started working ... Done a bit till now ..!!

**Comment by chinnichaitanya** [comment]
Push your code.

**Comment by sumanasusmitha** [comment]
Create a personal folder of yours and push your code and reply updates

**Comment by nitishkumarranjan** [comment]
I have pushed in the login_app repository

**Comment by chinnichaitanya** [comment]
Make a folder in `personal` folder and put the code in that. 
Why did you create your own repo and pushed into it ?

**Comment by chinnichaitanya** [comment]
Dude do this fast.

**Comment by sumanasusmitha** [comment]
@nitishkumarranjan reply with updates and clear the issues!

**Comment by chinnichaitanya** [comment]
@nitishkumarranjan Integrate it with AngularJS and push it to your personal folder.

**Comment by nitishkumarranjan** [comment]
i have uploaded the codes in the personal folder...

**Comment by chinnichaitanya** [comment]
@nitishkumarranjan  There are a few changes,
 - [ ] Separate the `css` code and `js` code and put them in separate files. Don't use them inline.
 - [ ] The link to `Login.html` page from `Registration.html` page seems to be broken. Fix that.
 - [ ] Use nice names for your controllers. Like `registrationCtrl` and `loginCtrl` etc.,
 - [ ] Use `bootstrap` classes and make it responsive. Not your own css.
 - [ ] Use bootstrap's `btn-group` [class](http://getbootstrap.com/components/) for the `Login` and `Registration` buttons.

**Comment by nitishkumarranjan** [comment]
I have updated the codes...just check it and let me know if it has issues

**Comment by chinnichaitanya** [comment]
@sumanasusmitha @sai-akshaya Can you look into this ?

**Comment by sai-akshaya** [comment]
Will do

On Mon, Aug 24, 2015 at 2:11 PM, Chinni Chaitanya <notifications@github.com>
wrote:

> @sumanasusmitha <https://github.com/sumanasusmitha> @sai-akshaya
> <https://github.com/sai-akshaya> Can you look into this ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShaastraWebops/Frontend-2016/issues/6#issuecomment-134097738>
> .
>



-- 
Regards,

Sai Akshaya
Second Year Undergraduate
Mechanical Engineering
IIT Madras

**Comment by sai-akshaya** [comment]
So I guess the spelling for register is wrong while linking login and register. Correct that for teh broken link. Otherwise everything else seems to be in place

**Comment by chinnichaitanya** [comment]
@nitishkumarranjan What I meant was to use **button-groups** and **not** tabs. Modify it ASAP.

**Comment by nitishkumarranjan** [comment]
Done ..just check it once

**Comment by chinnichaitanya** [comment]
@nitishkumarranjan I asked you to put all the styles in separate file. Don't use `<style>...</style>` tags.

**Comment by chinnichaitanya** [comment]
To add to that, the link to registration page is broken. You made typo there. Fix that also.
