### ISSUE TITLE
Menu bar

### ISSUE THREAD

**Issue by chinnichaitanya** [ShaastraWebops/Frontend-2016#7]
This might take some time. The data is not static here. Again we use ```$http``` requests to get the events, workshops etc.

Menu is used in all pages so this must be modular.

Refer **13.jpg** and **14.jpg** in the [drive](https://drive.google.com/folderview?id=0B41bGb29AKWqMURrd1lfVWR6WE0&usp=sharing) folder.

**Comment by AnandJM** [comment]
acknowledged

**Comment by chinnichaitanya** [comment]
Any updates ?

**Comment by AnandJM** [comment]
Right now I don't have a good net connection...will start working on 12th

**Comment by chinnichaitanya** [comment]
Any updates ?

**Comment by AnandJM** [comment]
made menu  page but need to put the jquery  in the angularjs controller file

**Comment by chinnichaitanya** [comment]
@AnandJM Any updates on this ??

**Comment by AnandJM** [comment]
Converted to angularjs and included social media icons

**Comment by chinnichaitanya** [comment]
@AnandJM A few changes,
- [ ] Make the menu bar occupy the complete height of the browser. 
- [ ] I find a *vertical-scroll-bar* appearing in my browser. Fix that.
- [ ] Can you make a smooth accordion animation on clicking tabs with the dropdown ? Right now it is appearing suddenly and is not looking good.

Make an update after completing those.

**Comment by chinnichaitanya** [comment]
@AnandJM Any updates ??

**Comment by AnandJM** [comment]
tried to make it accordion using slideUp() and slideDown() in jquery but
when it was put in the angular directive...it goes up and down twice due to
some problem. ...trying to fix that

**Comment by sumanasusmitha** [comment]
Updates?!

**Comment by AnandJM** [comment]
made the accordion using css. Included another folder with the jquery version. The jquery one slides up and down more than once on each click which is a problem.If this can be fixed i feel that this could be a better solution than using css. Please look into this and suggest solutions if any.

**Comment by chinnichaitanya** [comment]
@sumanasusmitha ?

**Comment by chinnichaitanya** [comment]
Ok the first one looks good. But it only occurs on clicking on the *right arrow*. Ideally, the animation should be happening on clicking on the bar itself.
Remember performance of CSS > performance of JavaScript.

**Comment by AnandJM** [comment]
okay will modify it to make it work for the whole bar

**Comment by AnandJM** [comment]
made it for the whole bar now

**Comment by chinnichaitanya** [comment]
@AnandJM 
 - [ ] Put scroll bar on the menu bar if it exceeds the viewport
 - [ ]  Make the *hamburger* menu icon with the same animation and add toggle feature on clicking it similar to Shaastra 2015 page.

**Comment by AnandJM** [comment]
Added hamburger and scroll

**Comment by chinnichaitanya** [comment]
@AnandJM Good work! But I see on clicking the close button, the menu just hides. There is no transition or anything like when it appears. So make a transition on closing the menu and put an update. The rest looks awesome.

**Comment by AnandJM** [comment]
new update with social icons outside and top menubar

**Comment by chinnichaitanya** [comment]
@sumanasusmitha @sai-akshaya Can you look into this ?

**Comment by sai-akshaya** [comment]
Great job (y). Seems fine to me

**Comment by chinnichaitanya** [comment]
@AnandJM A few things,
 - [ ] Put the top menubar in separate folder and the side menu bar in separate folder.
 - [ ] The animation to close the side menu bar is still not there. Add it.
